### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by vinitv** [PathriK/GaanaExtractor#6]
Looks like they have changed the way their API used to work.

**Comment by PathriK** [comment]
its not working on any songs?

**Comment by vinitv** [comment]
Yes didn't work on any playlist or album

**Comment by avdheshgoyadi** [comment]
It did worked for about 15 songs of a total of 600, but not for most. Please help.

**Comment by PathriK** [comment]
As far as i saw they have started using a new API and the old API is also working. But the problem is, most of the songs they have moved to the new API and only some are available in the old one. 

Since there is no documents on their new API, its difficult for me to update the App :( 

Will try to see if I can some how make it work though but not sure when and how I am gonna make it work though :|

**Comment by PathriK** [comment]
Hi
After a long time have released a new version....
https://github.com/PathriK/GaanaExtractor/releases/tag/v2.0-BETA
Now it should be able to convert nearly all the songs..
Please try it out and let me know if the issues are fixed..
